---
- name: Add Homebrew taps
  community.general.homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items:
    - homebrew/cask
    - homebrew/cask-versions

- name: Install Homebrew Formulas
  community.general.homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: yes
    upgrade_all: yes
  with_items:
    - aws-vault
    - chamber
    - direnv
    - git
    - git-extras
    - node
    - pyenv
    - zsh
    - zlib
    - youtube-dl
    - ffmpeg
    - autojump
    - wget
    - hub
    - autopep8

- name: Install Casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    greedy: yes
    accept_external_apps: yes
    update_homebrew: yes
    upgrade_all: yes
  with_items:
    - 1password
    - bartender
    - dropbox
    - firefox
    - iterm2
    - microsoft-teams
    - pycharm
    - slack
    - spectacle
    - spotify
    - zoomus
    - mark-text
    - bettertouchtool
    - sublime-text
    - sublime-merge
    - dozer
    - bunch
    - alfred
