---
- name: Add Homebrew taps
  community.general.homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items:
    - homebrew/cask
    - homebrew/cask-versions

- name: Install Homebrew Formulas
  community.general.homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: yes
    upgrade_all: yes
  with_items:
    - autojump
    - autopep8
    - chamber
    - direnv
    - ffmpeg
    - git
    - git-extras
    - htop
    - hub
    - ipython
    - jfrog-cli
    - jq
    - m-cli
    - minikube
    - ncdu
    - node
    - pipenv
    - pipx
    - pyenv
    - tfenv
    - thefuck
    - wget
    - youtube-dl
    - zlib
    - zsh

- name: Install Casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    greedy: yes
    accept_external_apps: yes
    update_homebrew: yes
    upgrade_all: yes
  with_items:
    - 1password
    - alfred
    - bettertouchtool
    - boop
    - bunch
    - dozer
    - firefox
    - iterm2
    - mark-text
    - numi
    - postman
    - pycharm
    - rectangle
    - slack
    - spotify
    - sublime-merge
    - sublime-text
    - boop
    - https://raw.githubusercontent.com/Mortennn/FiScript/master/fiscript.rb 

